server:
  ssl:
    enabled: true
    key-store: keystore.p12
    key-store-password: gozld18
    key-store-type: PKCS12
    key-ailas: bns-ssl
  port: 8443

# port: 8080
spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: manager
    url: jdbc:mysql://localhost:3306/social_sign?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.hbm2ddl.auto: update
    generate-ddl: true
    show-sql: true
  messages:
    basename: i18n/exception
    encoding: UTF-8